### ISSUE TITLE
Dependency Error on New Install

### ISSUE THREAD

**Issue by ghost** [TommyTran732/Fedora-CoreOS-Ignition#3]
Don’t know if this an error without your fcc or fcos. I am using compose.yml.

`un 10 00:16:20 localhost.localdomain rpm-ostree[1046]: Changes queued for next boot. Run "systemctl reboot" to start a reboot
Jun 10 00:16:21 localhost.localdomain rpm-ostree[1732]: Checking out tree 6d0ca50...done
Jun 10 00:16:21 localhost.localdomain rpm-ostree[1732]: Resolving dependencies...done
Jun 10 00:16:21 localhost.localdomain rpm-ostree[1732]: error: Could not depsolve transaction; 1 problem detected:
Jun 10 00:16:21 localhost.localdomain rpm-ostree[1732]:  Problem: package sssd-idp-2.7.0-1.fc36.x86_64 requires libsss_debug.so()(64bit), but none o>
Jun 10 00:16:21 localhost.localdomain rpm-ostree[1732]:   - package sssd-idp-2.7.0-1.fc36.x86_64 requires sssd-common = 2.7.0-1.fc36, but none of th>
Jun 10 00:16:21 localhost.localdomain rpm-ostree[1732]:   - conflicting requests
Jun 10 00:16:21 localhost.localdomain systemd[1]: postinst.service: Main process exited, code=exited, status=1/FAILURE
Jun 10 00:16:21 localhost.localdomain systemd[1]: postinst.service: Failed with result 'exit-code'.
Jun 10 00:16:21 localhost.localdomain systemd[1]: Failed to start postinst.service - Initial System Setup. `

**Comment by ryanrambharose** [comment]
Fixed by reboot sorry for the confusion

**Comment by ghost** [comment]
Also when I try to install a docker container:

`docker: Error response from daemon: failed to create shim task: OCI runtime create failed: reading spec: SELinux is not supported: system_u:system_r:container_t:s0:c81,c215: unknown. `

**Comment by TommyTran732** [comment]
You need to pass --security-opt label=disable for the containers. This is not a problem with the Ignition configuration.

**Comment by Roeda** [comment]
Hello @TommyTran732, I am trying to use your ignition file on a baremetal rpi4.
I unfortunately get 4 Failed Units:
  docker.service
  gvisor-updater.service
  postinst.service
  docker.socket

all with (code=exited, status=203/EXEC)
Failed at step EXEC spawning /usr/bin/sudo: Permission denied

since it's a selinux issue, it may be related to the initial reported issue ?

thank you very much for your help
