### ISSUE TITLE
recommendations for ARM64 Kernel arguments ... ?

### ISSUE THREAD

**Issue by Roeda** [TommyTran732/Fedora-CoreOS-Ignition#6]
Hello @TommyTran732,
for using coreos on a RPI4, could you recommend Kernel Arguments for arm64, or a way to acquire them ?
 
thank you in advance.

**Comment by TommyTran732** [comment]
Hi,

I do not have any specific kargs recommendation for aarch64. I just apply every mitigation option available across the board. If a karg doesn't work for the hardware, it will just get ingored and there will not be any problem. The exception is stuff like the Intel Wifi driver which breaks with the kargs on recent kernels (but then these are server deployments, so why would we care about WiFI drivers?).

If you wanna find more kargs, you have to find them in the kernel docs. Please let me know if you find anything interesting.
