### ISSUE TITLE
hardened Docker container config example ?

### ISSUE THREAD

**Issue by Roeda** [TommyTran732/Fedora-CoreOS-Ignition#7]
Hello,
since I am trying to expose my self hosted server to the internet. I am wondering if you have hardened your docker container deployments. if so, could you please share an example please ?
I read through the documentation about:
1- configuring the container to use an unprivileged user 
2- limiting capabilities of the container (--cap-drop)
3- Preventing in-container privilege escalation: (allowPrivilegeEscalation: false)
4- maybe also using Seccomp and AppArmor

as much as this is doable in a normal linux distribution. I am a beginner in Systemd and coreos and I struggle to find guides or documentation of a hardened deployment. 
(I haven't contemplated the fully rootless docker as it comes with it's limitations, and you're ignition config using gVisor seems good for my use case.)

thank you very much

**Comment by TommyTran732** [comment]
Does this help? https://privsec.dev/posts/linux/docker-and-oci-hardening/

Personally, I drop all capabilities and add readd the ones that are truely needed. `no-new-privileges: true` is always used. If I can force a container to run as non-root, I do that. If I can force containers to run in with `read_only: true`, I do that as well.
